apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-env
data:
  POSTGRES_HOST: "udacity-instance.ch6aqzxndogx.us-east-1.rds.amazonaws.com"
  POSTGRES_DB: "postgres"
  AWS_BUCKET: "udacity-instance"
  AWS_REGION: "us-east-1"
  AWS_PROFILE: "default"
  JWT_SECRET: "testing"
  URL: "http://localhost:8100"
